### ISSUE TITLE
Port other steps and pipelines

### ISSUE THREAD

**Issue by zonca** [oirlab/liger_iris_pipeline#63]
@astrobc1 great job on #62, I think you can go ahead and port all other steps and pipelines.

I suggest this order:

* individual steps
* pipelines (just `image2` if I'm not mistaken)
* steps/pipelines that mentions subarrays (I remember they were tricky)

Please 1 separate pull request for each test case.
If you ever get stuck, please still open a pull request with partial work and explain what is the issue.

**Comment by astrobc1** [comment]
@zonca I ported `assign_wcs` on a new branch. One minor change I don't quite understand was checking for membership in a DataModel's `meta` attribute (previously was `if attr not in meta`, see Note):

https://github.com/oirlab/liger_iris_pipeline/blob/1cc4f134610946b07f54ed1ce02ec41fa9961707/liger_iris_pipeline/assign_wcs/assign_wcs.py#L30

But the test passes. Should we PR/merge before I move onto the next `Step`?

**Comment by zonca** [comment]
@astrobc1 very good,
while I review #67, please start to work on another step, make sure you start again from the `main` branch instead of the branch of #67, we do not want the same commits to be in 2 branches.

**Comment by zonca** [comment]
> @zonca I ported `assign_wcs` on a new branch. One minor change I don't quite understand was checking for membership in a DataModel's `meta` attribute (previously was `if attr not in meta`, see Note):
> 
> https://github.com/oirlab/liger_iris_pipeline/blob/1cc4f134610946b07f54ed1ce02ec41fa9961707/liger_iris_pipeline/assign_wcs/assign_wcs.py#L30
> 
> But the test passes and I created PR #67.

I guess this was a bug either in an older version of `jwst` or in `iris_pipeline` itself, it looks good now.

**Comment by zonca** [comment]
@astrobc1 I fixed the strange issue we had in Github Actions in https://github.com/oirlab/liger_iris_pipeline/commit/ee3203b6f514f489b234e13161cbc2420519bde9

so please rebase your current branches on master so you can pick up this commit and we can have the tests properly running in Github Actions

**Comment by astrobc1** [comment]
@zonca Looking at what's next. Remaining .ipynb files are:

run_image2_subarray.ipynb
test_create_subarray_dataset.ipynb

**Comment by zonca** [comment]
@astrobc1 great, it would be nice to get them done by Tuesday so we can plan for what comes next.
Would you be able to do that? Otherwise I can take care of these last 2.

**Comment by zonca** [comment]
@astrobc1 there is als o#70 to finalize

**Comment by astrobc1** [comment]
Sorry I don't think GitHub notifies fixed comments. I can take care of 2-4 above by Tuesday.

**Comment by zonca** [comment]
> Sorry I don't think GitHub notifies fixed comments. I can take care of 2-4 above by Tuesday.

Good, I'll be on alert for review requests

**Comment by zonca** [comment]
@astrobc1 with #82 we are done, great job! `liger_iris_pipeline` is completely ported to the new version of jwst.
Next we can cleanup the docs and plan for the next steps.
